# insuLin_Guide/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=insuLin_Guide_db
      - POSTGRES_USER=insuLin_Guide_user
      - POSTGRES_PASSWORD=Tmttd106!@ # 실제 비밀번호로 변경
      - POSTGRES_HOST_AUTH_METHOD=trust

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env

    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=insuLin_Guide_db
      - POSTGRES_USER=insuLin_Guide_user
      - POSTGRES_PASSWORD=Tmttd106!@ # 실제 비밀번호로 변경
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: