# Simon/docker-compose.yml
services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U insuLin_Guide_user -d insuLin_Guide_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env

    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Nginx 설정 파일 연결
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      # Let's Encrypt 인증서 파일들을 컨테이너 내부로 연결
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # Let's Encrypt 갱신용 폴더 연결
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: