# Generated by Django 5.2.4 on 2025-08-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('ai', 'AI'), ('user', '사용자')], max_length=10),
        ),
    ]
